<% if (it.formatters) { -%>
name: Format CSS
on:
  pull_request:
    paths:
      - '**.css'
      - '**.scss'
      - '**.sass'
      - '**.less'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: '<%= it.packageManager.name %>'

      <%_ if (it.packageManager.name === "npm") { %>
      - run: npm ci
      <%_ } else { %>
      - run: yarn
      <% } -%>

      <%_ if (it.formatters.prettier) { %>
      - run: npx prettier --no-error-on-unmatched-pattern --check "**.css" "**.scss" "**.sass" "**.less"
      <% } -%>
<% } -%>
