<% if (it.linters) { -%>
name: Lint CSS
on:
  pull_request:
    paths:
      - '**.css'
      - '**.scss'
      - '**.sass'
      - '**.less'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: '<%= it.packageManager.name %>'

      <%_ if (it.packageManager.name === "npm") { %>
      - run: npm ci
      <%_ } else { %>
      - run: yarn
      <% } -%>

      <%_ if (it.linters.stylelint) { %>
      - run: npx stylelint "**/*.css" "**/*.scss" "**/*.sass" "**/*.less"
      <% } -%>
<% } -%>
