name: Lint Python
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: <%= it.version %>
      - run: python -m pip install flake8
      - run: flake8
